apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: angular-container
        image: infinity523/boot-app:latest

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: bootservice
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: spring
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer